### ISSUE TITLE
Name clash with django-command-log

### ISSUE THREAD

**Issue by jayvdb** [yunojuno/django-management-command-log#8]
The setup.py lists name `django-command-log`, which clashes with https://pypi.org/project/django-command-log/ , and causes some problems, e.g. with distro packaging.  Most distros now require Python code to be uploaded to PyPI and their package name then reflects the PyPI package name.

Also the package directory is `command_log` which also clashes with it.  However this is less problematic, as the two packages can be prevented from overwriting each other by using `Conflicts: ...` in the RPM spec.

**Comment by hugorodgerbrown** [comment]
Hi @jayvdb, thanks for the comment. In fact, this Github project _is_ that PyPI package (https://pypi.org/project/django-command-log/) - they are one and same thing.

The Github project name is the result of some historical clash which tbh I can't remember now, but I don't think that is relevant (the GH name).

Regarding the comment "Most distros now require Python code to be uploaded to PyPI and their package name then reflects the PyPI package name" - this project is already uploaded to PyPI, under the package name `django-command-log`.

Github project name: `django-management-command-log`
PyPI Package name: `django-command-log`
Import package name: `command_log`

There isn't another package on PyPI called `command_log`, or `django-command-log` - I don't really understand the problem here?

**Comment by jayvdb** [comment]
Oh, hmmm ... it looks like I got confused.  I thought there was another one.
Apologies.
